### ISSUE TITLE
2.4.0

### ISSUE THREAD

**Issue by rlatapy-luna** [snapcall/snapcall_sdk_android#1]
Where is the v2.4.0?

![image](https://user-images.githubusercontent.com/45555889/140714149-ac8ba47e-6cbe-4ff8-868b-1d805d99baba.png)

Thanks

**Comment by pnoyelle** [comment]
The doc version as not been updated, The 2.4.0  was a broken build and was deleted you should use lattest version (https://github.com/snapcall/snapcall_sdk_android/releases).

**Comment by rlatapy-luna** [comment]
Ok thanks, maybe you should consider stop doing pre-releases so we can see the latest version and receive notification from Github on release...
![image](https://user-images.githubusercontent.com/45555889/140719839-51a21f6e-59e8-41c6-bd46-5fd24dd39c60.png)
![image](https://user-images.githubusercontent.com/45555889/140719875-de6ba16f-b00b-4ed0-ab5d-66d0315e714e.png)
